tempthree/appthree/urls.py
from django.urls import path
from appthree import views

app_name = 'appthree'

urlpatterns = [
    path('index/', views.index, name='index'), 
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name = 'relative') 
]

tempthree/tempthree/urls.py
from django.contrib import admin
from django.urls import path, include
from appthree import views, urls

urlpatterns = [
    path('', views.index),
    path("", include(urls)),
    path('admin/', admin.site.urls),
]

tempthree/appthree/models.py
from django.db import models

# Create your models here.

tempthree/appthree/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'title':'hello universe', 'number':1000}
    return render(request, 'appthree/index.html', context_dict)

def other(request):
    return render(request, 'appthree/other.html')

def relative(request):
    return render(request, 'appthree/relative_url.html')

tempthree/templates/appthree/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'appthree/CSS/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-static-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'appthree:index' %}">BRAND</a>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'appthree:other' %}" class="nav-link active" aria-current="page">Other</a>
            </li>
          </ul>
        </div>
    </nav>
    
    <div class="container"> 
        {% block body_block %}
        
        {% endblock %}

    </div>
</body>
</html>

tempthree/templates/appthree/index.html
<!DOCTYPE html>
{% extends "appthree/base.html"%}
    {% block body_block %}
        <h1>WELCOME TO INDEX PAGE</h1>
           <b>{{ title|cut:"hello" }}</b> 
            <b>{{ number|add:"22" }}</b>
    {% endblock %}
    

tempthree/templates/appthree/other.html
<!DOCTYPE html>
{% extends "appthree/base.html"%}
    {% block body_block %}

        <h1>WELCOME TO OTHER PAGE</h1>
        <h2>This is an example of template inheritance</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora sed dolores, cupiditate dicta maiores dolorum illo consequuntur unde magnam inventore sit nemo aspernatur quo sunt tenetur beatae delectus. Assumenda, earum.</p>
    {% endblock %}

tempthree/templates/appthree/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative Url</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE PAGE</h1>
    <a href="{% url 'appthree:other' %}">OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'appthree:index' %}">LINK TO INDEX</a>
</body>
</html>